medical_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      dbname: medical_warehouse
      user: postgres
      password: postgres
      schema: staging
      threads: 4